# Generated by Django 4.1.7 on 2023-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ratingstar_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url_trailer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
