# Generated by Django 4.1.7 on 2023-05-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': 'Отзыв и оценка', 'verbose_name_plural': 'Отзыв и оценка'},
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_ratio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_total',
            field=models.IntegerField(default=0),
        ),
    ]
