# Generated by Django 4.1.7 on 2023-05-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_factsmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_url',
            field=models.URLField(default='', verbose_name='IMDb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_url',
            field=models.URLField(default='', verbose_name='Кинопоиск'),
        ),
    ]
