# Generated by Django 4.1.7 on 2023-06-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_alter_movie_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0, verbose_name='Рэйтинг IMDb'),
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_rating',
            field=models.FloatField(default=0, verbose_name='Рэйтинг Кинопоиска'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='adding_movie',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='Какие пользователи добавили фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_ratio',
            field=models.FloatField(default=0, verbose_name='Соотношение оценок'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_total',
            field=models.IntegerField(default=0, verbose_name='Общее количество оценок'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Положительная оценка'), ('down', 'Отрицательная оценка')], max_length=200, verbose_name='Оценка'),
        ),
    ]
