# Generated by Django 4.1.7 on 2023-06-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_movie_adding_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='kinopoisk_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг Кинопоиска'),
        ),
    ]
