# Generated by Django 4.1.7 on 2023-06-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_movie_kinopoisk_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='draft',
        ),
    ]
