# Generated by Django 4.1.7 on 2023-06-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_movie_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг IMDb'),
        ),
    ]
