# Generated by Django 4.1.7 on 2023-06-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_actor_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url_image',
            field=models.URLField(default='', verbose_name='URL картинки для рассылки'),
        ),
    ]
