# Generated by Django 4.1.7 on 2023-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_movie_number_of_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Был отправлен как рассылка'),
        ),
    ]
