# Generated by Django 4.2.2 on 2023-07-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_movie_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created'], 'verbose_name': 'Отзыв и оценка', 'verbose_name_plural': 'Отзыв и оценка'},
        ),
        migrations.AddField(
            model_name='movie',
            name='url_excerpt_movie',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
