# Generated by Django 4.2.2 on 2023-07-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_review_options_movie_url_excerpt_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='height',
            field=models.FloatField(blank=True, default=0, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.SlugField(max_length=130, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_excerpt_movie',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='URL отрывка из фильма (необязательно)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_trailer',
            field=models.CharField(default='', max_length=1000, verbose_name='URL трейлера'),
        ),
    ]
