# Generated by Django 4.2.2 on 2023-07-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_actor_height_alter_movie_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(default=0, help_text='Указывать в минутах', verbose_name='Продолжительность фильма (или одной серии)'),
        ),
    ]
