# Generated by Django 4.2.2 on 2023-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_actor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Отправлен как рассылка'),
        ),
    ]
