# Generated by Django 4.1.7 on 2023-06-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_movie_age_rating_movie_eng_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(default=0, help_text='Указывать в минутах', max_length=1000, verbose_name='Продолжительность фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age_rating',
            field=models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, verbose_name='Возрастной рейтинг'),
        ),
    ]
