# Generated by Django 4.1.7 on 2023-06-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_movie_movie_duration_alter_movie_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_duration',
            field=models.IntegerField(default=0, help_text='Указывать в минутах', verbose_name='Продолжительность фильма'),
        ),
    ]
