# Generated by Django 4.1.7 on 2023-06-05 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_movie_imdb_rating_movie_kinopoisk_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='adding_movie',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL, verbose_name='Какие пользователи добавили фильм'),
        ),
    ]
