# Generated by Django 4.1.7 on 2023-06-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_movie_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url_image',
            field=models.URLField(blank=True, default='', verbose_name='URL картинки для рассылки'),
        ),
    ]
