# Generated by Django 4.1.7 on 2023-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Была отправлен как рассылка'),
        ),
    ]
