# Generated by Django 4.2.2 on 2023-06-24 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionuser',
            options={'ordering': ['-created'], 'verbose_name': 'Вопрос из форума', 'verbose_name_plural': 'Вопрос из форума'},
        ),
        migrations.AlterField(
            model_name='questionuser',
            name='question',
            field=models.TextField(default='', max_length=10000, verbose_name='Вопрос'),
        ),
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='Отзыв')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('question_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.questionuser', verbose_name='Вопрос пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв к вопросу',
                'verbose_name_plural': 'Отзыв к вопросу',
                'ordering': ['-created'],
            },
        ),
    ]
