# Generated by Django 4.2.2 on 2023-06-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_questionuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuser',
            name='question',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
    ]
