# Generated by Django 4.2.2 on 2023-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_questionuser_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuser',
            name='question',
            field=models.TextField(verbose_name='Раскройте суть вопроса'),
        ),
    ]
