# Generated by Django 4.2.2 on 2023-06-26 18:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_questionuser_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionuser',
            name='question',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Раскройте суть вопроса'),
        ),
        migrations.AlterField(
            model_name='questionuser',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок (обязательное поле)'),
        ),
    ]
