# Generated by Django 4.2.2 on 2023-07-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_questionuser_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewquestion',
            options={'ordering': ['created'], 'verbose_name': 'Отзыв к вопросу', 'verbose_name_plural': 'Отзыв к вопросу'},
        ),
    ]
