# Generated by Django 4.1.7 on 2023-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_review_options_movie_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_ratio',
            field=models.FloatField(default=0),
        ),
    ]
