# Generated by Django 4.1.7 on 2023-06-12 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата рождения'),
        ),
    ]
