# Generated by Django 4.1.7 on 2023-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_actor_country_actor_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='eng_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя на английском'),
        ),
    ]
