# Generated by Django 4.1.7 on 2023-06-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_movie_url_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_of_seasons',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество сезонов (если добавляете сериал)'),
        ),
    ]
