# Generated by Django 4.2.2 on 2023-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_questionuser_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionuser',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='questionuser',
            name='question',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Раскройте суть вопроса'),
        ),
    ]
