# Generated by Django 4.1.7 on 2023-05-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
