# Generated by Django 4.2.2 on 2023-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_reviewnews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewnews',
            options={'ordering': ['created'], 'verbose_name': 'Комментарии к новостям', 'verbose_name_plural': 'Комментарии к новостям'},
        ),
        migrations.AlterField(
            model_name='reviewnews',
            name='body',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
