# Generated by Django 4.2.2 on 2023-06-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_questionuser_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionuser',
            name='image',
        ),
    ]
